web:
    container_name: # set name here
    build: web
    ports:
        - "80:80"
    volumes:
        - ../:/var/www
    links:
        - redis
        - db

redis:
    container_name: # set name here
    image: redis
    ports:
        - "6379:6379"

db:
    container_name: # set name here
    build: db
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD={root}
